### ISSUE TITLE
Support AWS client "profiles" in YAML config

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-aws#13]
_AWS 2 only_

Currently profile credentials provider is added explicitly via the extender. And Bootique app can not specify the name of the profile. So it is either `default` or is controlled via `-Daws.profile` (not the Bootique style). Would be nice to be able to switch profile names (and switch between explicit credentials and profiles) via Bootique configuration.

Consider the current configuration:
```yaml
aws:
  accessKey: ...
  secretKey: ...
```
To make the new one work, we introduced **a breaking change** in the config structure. There is a new polymorphic `credentials` object in configuration:

```yaml
# explicit credentials
aws:
  credentials:
     accessKey: ...
     secretKey: ...
```

```yaml
# profile credentials
aws:
  credentials:
     type: profile
     profileName: myProfile
```
