### ISSUE TITLE
Temporary credentials with "sessionToken"

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-aws#14]
_AWS 2 Only_

Sometimes apps need to use [temporary credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) (e.g. in development when a dev account requires MFA, there's no way to use regular credentials in the app). Temporary are the same as regular ones, in that they have access and secret keys, but  they also have a `sessionToken` parameter. So going to add `sessionToken` as an extra configuration property, and create  a corresponding credentials provider if the session token is present.

```yaml
aws:
  credentials:
     accessKey: ...
     secretKey: ...
     sessionToken: ...
```
