### ISSUE TITLE
Allow mapping S3 bucket/folder locations via YAML

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-aws#3]
Same as HttpClient, where we allow mapping URLs ("targets") to symbolic names, I think it will be advantageous to allow S3 URLs to be defined in YAML, which would enable config-driven switching between environments. E.g.:

```yaml
awss3:
  targets:
    a:
      url: "s3://mybucket/mypath"
```
