### ISSUE TITLE
Integrate EndpointConfiguration in each service config

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-aws#7]
Integrate AWS EndpointConfiguration in the AWS config. This helps with unit tests (using frameworks like Localstack). Configure as:

```yaml
aws:
  serviceEndpoint: <url>
  signingRegion: <region name>
```

**Comment by andrus** [comment]
Reopening... "endpointConfiguration" is a property of each service, not a common config. Need to reimplement accordingly.

**Comment by andrus** [comment]
Done. Module configs would now look as this:

```yaml
awss3:
  serviceEndpoint: <url>
  signingRegion: <region name>
```

```yaml
awssecrets:
  serviceEndpoint: <url>
  signingRegion: <region name>
```

and so on
